version: "3.9"

services:
  edge-api:
    build: .
    container_name: edge-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - edge-net

  mysql:
    image: mysql:8.0
    container_name: mysql-edge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dedalus
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - edge-net

networks:
  edge-net:

volumes:
  mysql_data:
